// Keep the loader's short lines and code-like punctuation in both languages.
// Brand glyphs and existing language-neutral ASCII labels use the shared fallback.
export const startupLoaderEnglish: Record<string, string> = {
  'ОТ ВОПРОСА К РЕШЕНИЮ': 'FROM QUESTION TO ANSWER',
  'ИССЛЕДОВАНИЕ АУДИТОРИИ': 'AUDIENCE RESEARCH',
  'ИНТЕРВЬЮ И НАБЛЮДЕНИЯ': 'INTERVIEWS / OBSERVATION',
  'ЦЕЛИ → СЦЕНАРИИ': 'GOALS → USER FLOWS',
  'КАРТА КОНТЕНТА': 'CONTENT MAP',
  'СМЫСЛОВАЯ СТРУКТУРА': 'CONTENT WITH STRUCTURE',
  'ПЕРВЫЙ ЭСКИЗ': 'FIRST SKETCH',
  'ПРОТОТИП В ДВИЖЕНИИ': 'PROTOTYPE IN MOTION',
  'ВИЗУАЛЬНЫЙ ЯЗЫК': 'VISUAL LANGUAGE',
  'КОНТРАСТ И ВОЗДУХ': 'CONTRAST / WHITE SPACE',
  'ТИПОГРАФИЧЕСКИЙ РИТМ': 'TYPOGRAPHIC RHYTHM',
  'СЕТКА БЕЗ ОГРАНИЧЕНИЙ': 'A FLEXIBLE GRID',
  'СВЯЗЬ МЕЖДУ ЭКРАНАМИ': 'CONNECTED SCREENS',
  'МОБИЛЬНЫЕ СЦЕНАРИИ': 'MOBILE USER FLOWS',
  'АНИМАЦИЯ СО СМЫСЛОМ': 'ANIMATION WITH PURPOSE',
  'ОБРАТНАЯ СВЯЗЬ': 'FEEDBACK',
  'ПРОВЕРКА НА ПРАКТИКЕ': 'TESTED IN PRACTICE',
  'ДЕТАЛИ СОЗДАЮТ ОПЫТ': 'DETAILS SHAPE EXPERIENCE',
  'АРХИТЕКТУРА ПРОЕКТА': 'PROJECT ARCHITECTURE',
  'КОМПОНЕНТЫ И СОСТОЯНИЯ': 'COMPONENTS / STATES',
  'ДАННЫЕ → ИНТЕРФЕЙС': 'DATA → INTERFACE',
  'ЗАЯВКА БЕЗ ПОТЕРЬ': 'EVERY INQUIRY CAPTURED',
  'БОТ ОТВЕЧАЕТ КЛИЕНТУ': 'BOT REPLIES TO CLIENT',
  'CRM СОХРАНЯЕТ ИСТОРИЮ': 'CRM KEEPS THE HISTORY',
  'СЕРВИСЫ РАБОТАЮТ ВМЕСТЕ': 'SERVICES WORK TOGETHER',
  'ПОНЯТНЫЕ ОШИБКИ': 'CLEAR ERROR MESSAGES',
  'БЕЗОПАСНЫЕ ФОРМЫ': 'SECURE FORMS',
  'СЕМАНТИЧЕСКАЯ РАЗМЕТКА': 'SEMANTIC MARKUP',
  'ПОИСК НАХОДИТ СТРАНИЦЫ': 'PAGES SEARCH CAN FIND',
  'МЕДИА ЗАГРУЖАЮТСЯ БЫСТРО': 'FAST-LOADING MEDIA',
  'МЕНЬШЕ ЛИШНИХ ЗАПРОСОВ': 'FEWER REDUNDANT REQUESTS',
  'ПРОВЕРКА НА УСТРОЙСТВАХ': 'TESTING ACROSS DEVICES',
  'ТЕСТЫ ПОЛЬЗОВАТЕЛЬСКИХ ПУТЕЙ': 'USER JOURNEY TESTS',
  'ПЕРЕДАЧА КОМАНДЕ': 'TEAM HANDOVER',
  'ПОДДЕРЖКА ПОСЛЕ ЗАПУСКА': 'SUPPORT AFTER LAUNCH',
  'ИССЛЕДУЕМ ЗАДАЧУ': 'EXPLORE THE BRIEF',
  'СЛУШАЕМ КОМАНДУ': 'LISTEN TO THE TEAM',
  'НАХОДИМ СМЫСЛ': 'FIND THE PURPOSE',
  'СОБИРАЕМ СТРУКТУРУ': 'BUILD THE STRUCTURE',
  'СТРОИМ ПУТЬ': 'MAP THE JOURNEY',
  'ПРОВЕРЯЕМ ГИПОТЕЗЫ': 'TEST ASSUMPTIONS',
  'УБИРАЕМ ЛИШНЕЕ': 'REMOVE THE EXCESS',
  'ВЫСТРАИВАЕМ ИЕРАРХИЮ': 'DEFINE THE HIERARCHY',
  'НАСТРАИВАЕМ РИТМ': 'SET THE RHYTHM',
  'ВЫБИРАЕМ ТИПОГРАФИКУ': 'CHOOSE THE TYPE',
  'СОБИРАЕМ ПАЛИТРУ': 'BUILD THE PALETTE',
  'ДОБАВЛЯЕМ ХАРАКТЕР': 'ADD CHARACTER',
  'ПРОЕКТИРУЕМ СОСТОЯНИЯ': 'DESIGN THE STATES',
  'СВЯЗЫВАЕМ ЭКРАНЫ': 'CONNECT THE SCREENS',
  'СОЗДАЁМ ДВИЖЕНИЕ': 'CREATE MOTION',
  'УТОЧНЯЕМ ДЕТАЛИ': 'REFINE THE DETAILS',
  'ИНТЕРФЕЙС СО СМЫСЛОМ': 'INTERFACE WITH PURPOSE',
  'ФОРМА СЛЕДУЕТ ЗАДАЧЕ': 'FORM FOLLOWS THE BRIEF',
  'ПИШЕМ КОМПОНЕНТЫ': 'WRITE THE COMPONENTS',
  'СВЯЗЫВАЕМ ДАННЫЕ': 'CONNECT THE DATA',
  'АДАПТИРУЕМ ЭКРАНЫ': 'ADAPT THE LAYOUTS',
  'СОКРАЩАЕМ ЗАГРУЗКУ': 'REDUCE LOAD TIMES',
  'ОПТИМИЗИРУЕМ МЕДИА': 'OPTIMIZE MEDIA',
  'ПОДКЛЮЧАЕМ API': 'CONNECT THE APIS',
  'АВТОМАТИЗИРУЕМ ЗАЯВКИ': 'AUTOMATE INQUIRIES',
  'ТЕСТИРУЕМ СЦЕНАРИИ': 'TEST THE USER FLOWS',
  'ПРОВЕРЯЕМ ФОРМЫ': 'CHECK THE FORMS',
  'ОТЛАЖИВАЕМ АНИМАЦИЮ': 'DEBUG THE ANIMATION',
  'СОБИРАЕМ ОБРАТНУЮ СВЯЗЬ': 'GATHER FEEDBACK',
  'ЗАПУСКАЕМ ПРОДУКТ': 'LAUNCH THE PRODUCT',
  'РАЗВИВАЕМ РЕШЕНИЕ': 'DEVELOP IT FURTHER',
  'СТРАТЕГИЯ И ДИЗАЙН': 'STRATEGY / DESIGN',
  'САЙТЫ И СЕРВИСЫ': 'WEBSITES / SERVICES',
  'БРЕНД И КОММУНИКАЦИЯ': 'BRAND / COMMUNICATION',
  'ЛЕНДИНГИ И КАТАЛОГИ': 'LANDING PAGES / CATALOGS',
  'ИНТЕРАКТИВНЫЕ ИСТОРИИ': 'INTERACTIVE STORIES',
  'БOTЫ И CRM': 'BOTS / CRM',
  'ДАННЫЕ И ИНТЕГРАЦИИ': 'DATA / INTEGRATIONS',
  'СИСТЕМА ВМЕСТО ХАОСА': 'ORDER OUT OF CHAOS',
  'СМЫСЛ ВМЕСТО ШУМА': 'CLARITY THROUGH THE NOISE',
  'РИТМ В КАЖДОЙ ДЕТАЛИ': 'RHYTHM IN EVERY DETAIL',
  'ЛЮДИ В ЦЕНТРЕ': 'PEOPLE AT THE CENTER',
  'ОТ ИДЕИ ДО ЗАПУСКА': 'FROM IDEA TO LAUNCH',
  'СОЗДАЁМ ВМЕСТЕ': 'CREATE TOGETHER',
  '→ ВАШ СЛЕДУЮЩИЙ ПРОЕКТ': '→ YOUR NEXT PROJECT',
  'БРИФ И ИССЛЕДОВАНИЕ': 'BRIEF / RESEARCH',
  'СТРУКТУРА САЙТА': 'SITE STRUCTURE',
  'ПУТЬ ПОЛЬЗОВАТЕЛЯ': 'USER JOURNEY',
  ПРОТОТИП: 'PROTOTYPE',
  'ДИЗАЙН-СИСТЕМА': 'DESIGN SYSTEM',
  РАЗРАБОТКА: 'DEVELOPMENT',
  'COLOUR & CONTRAST': 'COLOR & CONTRAST',
  'ПРОВЕРЯЕМ ДЕТАЛИ': 'CHECK THE DETAILS',
  'ЗАПУСКАЕМ ПРОЕКТ': 'LAUNCH THE PROJECT',
  'РАЗВИВАЕМ ПРОДУКТ': 'DEVELOP THE PRODUCT',
  'СНАЧАЛА — ЗАДАЧА': 'FIRST, THE BRIEF',
  'ПОТОМ — РЕШЕНИЕ': 'THEN, THE SOLUTION',
  '→ СМЫСЛ В КАЖДОЙ ДЕТАЛИ': '→ PURPOSE IN EVERY DETAIL',
  'СТРОИМ ПОНЯТНЫЙ ПУТЬ': 'MAP A CLEAR PATH',
  ТИПОГРАФИКА: 'TYPOGRAPHY',
  'СЕТКА И КОМПОЗИЦИЯ': 'GRID / COMPOSITION',
  'ЦВЕТ И КОНТРАСТ': 'COLOR / CONTRAST',
  'СОСТОЯНИЯ ИНТЕРФЕЙСА': 'INTERFACE STATES',
  'ПЛАВНОЕ ДВИЖЕНИЕ': 'SMOOTH MOTION',
  'ЧИСТАЯ ЛОГИКА': 'CLEAR LOGIC',
  'ЗАЯВКА → БОТ → CRM': 'INQUIRY → BOT → CRM',
  АВТОМАТИЗАЦИЯ: 'AUTOMATION',
  'ИНТЕГРАЦИИ СЕРВИСОВ': 'SERVICE INTEGRATIONS',
  'ДАННЫЕ БЕЗ ПОТЕРЬ': 'NO DATA LOST',
  'БЫСТРАЯ ЗАГРУЗКА': 'FAST LOADING',
  'ПРОВЕРКА СЦЕНАРИЕВ': 'USER FLOW TESTS',
  'САЙТ ГОТОВ К ЗАПУСКУ': 'WEBSITE READY TO LAUNCH',
}
